version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
    ports:
     - "5432:5432"
  api:
    container_name: api
    build:
      context: .
    command: cargo run
    volumes:
      - .:/app
      - ./tmp/.cargo/registry:/root/.cargo/registry
      - ./tmp/.cache:/root/.cache
    depends_on:
      - postgres
    ports:
     - "28000:8000"
  web:
    container_name: web
    build:
      context: .
    working_dir: '/app/webapp'
    command: yarn run serve
    ports:
     - "28080:8080"
    volumes:
      - .:/app
    depends_on:
      - api
